/micro_ros_agent:
    transport: serial
    middleware: dds
    serial_baud: 115200
    serial_device: /Users/rhys/dev/ttyROS0
    refs_file: src/ardupilot/libraries/AP_DDS_Client/dds_xrce_profile.xml

/ardupilot:
    vehicle: ArduCopter
    frame: quad
    serial_baud: 115200
    serial_device: /Users/rhys/ttyROS1
